---
extends: default

rules:
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 1
  brackets:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 1
  line-length:
    max: 180
    level: warning
  truthy:
    check-keys: false
