---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-eu-west-1a
spec:
  minSize: 1
  maxSize: 1
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-eu-west-1b
spec:
  minSize: 1
  maxSize: 1
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-eu-west-1c
spec:
  minSize: 1
  maxSize: 1
