---
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: base.kind.tvld.tech
spec:
  configBase: s3://tvld-k8s-gitops-kops-state/lab.kind.tvld.tech
  masterInternalName: k8s.internal.kind.tvld.tech
  masterPublicName: k8s.lab.kind.tvld.tech
  networkCIDR: 172.10.0.0/16
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://tvld-k8s-gitops-kops-oidc
  subnets:
    - cidr: 172.10.32.0/19
      name: us-east-1a
      type: Private
      zone: us-east-1a
    - cidr: 172.10.64.0/19
      name: us-east-1b
      type: Private
      zone: us-east-1b
    - cidr: 172.10.96.0/19
      name: us-east-1c
      type: Private
      zone: us-east-1c
    - cidr: 172.10.0.0/22
      name: utility-us-east-1a
      type: Utility
      zone: us-east-1a
    - cidr: 172.10.4.0/22
      name: utility-us-east-1b
      type: Utility
      zone: us-east-1b
    - cidr: 172.10.8.0/22
      name: utility-us-east-1c
      type: Utility
      zone: us-east-1c
