---
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: base.kind.tvld.tech
spec:
  cloudConfig:
    manageStorageClasses: true
    awsEBSCSIDriver:
      enabled: true
  cloudLabels:
    Application: Kubernetes
    ManagedBy: Kops
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["elasticloadbalancing:*"],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": ["s3:GetEncryptionConfiguration"],
          "Resource": ["*"]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:GetEncryptionConfiguration"],
          "Resource": ["*"]
        }
      ]
  addons:
    - manifest: https://raw.githubusercontent.com/glebiller/kops-flux-addon/main/addon.yaml
  api:
    loadBalancer:
      class: Network
      type: Public
  authentication:
    aws:
      backendMode: CRD
      image: ghcr.io/glebiller/aws-iam-authenticator-arm:v0.5.3
      memoryRequest: 15Mi
      cpuRequest: 10m
      memoryLimit: 20Mi
      cpuLimit: 20m
  authorization:
    rbac: { }
  certManager:
    enabled: true
    managed: false
  channel: stable
  cloudControllerManager:
    cloudProvider: aws
    image: k8s.gcr.io/provider-aws/cloud-controller-manager:v1.23.1
  cloudProvider: aws
  clusterDNSDomain: cluster.local
  containerRuntime: containerd
  etcdClusters:
    - cpuRequest: 60m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: master-us-east-1a
          name: a
        - encryptedVolume: true
          instanceGroup: master-us-east-1b
          name: b
        - encryptedVolume: true
          instanceGroup: master-us-east-1c
          name: c
      memoryRequest: 500Mi
      name: main
    - cpuRequest: 25m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: master-us-east-1a
          name: a
        - encryptedVolume: true
          instanceGroup: master-us-east-1b
          name: b
        - encryptedVolume: true
          instanceGroup: master-us-east-1c
          name: c
      memoryRequest: 100Mi
      name: events
  iam:
    useServiceAccountExternalPermissions: true
    allowContainerRegistry: true
    legacy: false
  karpenter:
    enabled: true
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    cloudProvider: external
    cpuRequest: 200m
    cpuLimit: 500m
    memoryRequest: 700Mi
    memoryLimit: 1Gi
  kubeControllerManager:
    cloudProvider: external
  kubeDNS:
    provider: CoreDNS
    memoryLimit: 100Mi
    cpuRequest: 10m
    memoryRequest: 30Mi
    nodeLocalDNS:
      enabled: true
      memoryRequest: 12Mi
      cpuRequest: 5m
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
    cloudProvider: external
  kubernetesApiAccess:
    - 0.0.0.0/0
  networking:
    cilium:
      enableNodePort: true
      hubble:
        enabled: true
      memoryRequest: 128Mi
      cpuRequest: 10m
  nodeProblemDetector:
    enabled: false
    image: todo-arm-version
    memoryRequest: 32Mi
    cpuRequest: 10m
  nodeTerminationHandler:
    enabled: true
    enableSQSTerminationDraining: true
    managedASGTag: aws-node-termination-handler/managed
    prometheusEnable: true
    memoryRequest: 20Mi
    cpuRequest: 5m
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    enableAWSOIDCProvider: true
    additionalAudiences:
      - sts.amazonaws.com
  sshAccess:
    - 0.0.0.0/0
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
