---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-us-east-1a
  labels:
    kops.k8s.io/cluster: k8s-gitops-kops
spec:
  cloudLabels:
    Application: Kubernetes
    ManagedBy: Kops
  associatePublicIp: false
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t4g.medium
  minSize: 1
  maxSize: 1
  mixedInstancesPolicy:
    instances:
      - c6g.medium
      - m6g.medium
      - r6g.medium
      - t4g.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
    - us-east-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-us-east-1b
  labels:
    kops.k8s.io/cluster: k8s-gitops-kops
spec:
  cloudLabels:
    Application: Kubernetes
    ManagedBy: Kops
  associatePublicIp: false
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t4g.medium
  minSize: 1
  maxSize: 1
  mixedInstancesPolicy:
    instances:
      - c6g.medium
      - m6g.medium
      - r6g.medium
      - t4g.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
    - us-east-1b
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-us-east-1c
  labels:
    kops.k8s.io/cluster: k8s-gitops-kops
spec:
  cloudLabels:
    Application: Kubernetes
    ManagedBy: Kops
  associatePublicIp: true
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t4g.medium
  minSize: 1
  maxSize: 1
  mixedInstancesPolicy:
    instances:
      - c6g.medium
      - m6g.medium
      - r6g.medium
      - t4g.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
    - us-east-1c
